create schema if not exists ot_aquaculturestaffperformancems;

create table if not exists ot_aquaculturestaffperformancems.t_department (
  did integer generated by default as identity primary key,
  dname text not null,
  description text not null default '',
  ctime text not null default '',
  operator text not null default ''
);

create table if not exists ot_aquaculturestaffperformancems.t_position (
  pid integer generated by default as identity primary key,
  did integer not null references ot_aquaculturestaffperformancems.t_department(did) on delete cascade,
  pname text not null,
  description text not null default '',
  requirements text not null default ''
);

create table if not exists ot_aquaculturestaffperformancems.t_user (
  uid integer generated by default as identity primary key,
  did integer not null references ot_aquaculturestaffperformancems.t_department(did) on delete restrict,
  pid integer not null references ot_aquaculturestaffperformancems.t_position(pid) on delete restrict,
  username text not null unique,
  password text not null,
  identify text not null,
  name text not null,
  sex text not null default '',
  age text not null default '',
  birthdate text not null default '',
  idcard text not null default '',
  phone text not null default '',
  avatar text not null default 'user.jpg'
);

create table if not exists ot_aquaculturestaffperformancems.t_notice (
  nid integer generated by default as identity primary key,
  title text not null,
  notice text not null,
  ctime text not null default '',
  operator text not null default ''
);

create table if not exists ot_aquaculturestaffperformancems.t_live (
  lid integer generated by default as identity primary key,
  data text not null,
  remarks text not null,
  operator text not null default '',
  time text not null default ''
);

create table if not exists ot_aquaculturestaffperformancems.t_task (
  tid integer generated by default as identity primary key,
  uid integer not null references ot_aquaculturestaffperformancems.t_user(uid) on delete cascade,
  description text not null,
  stime text not null default '',
  etime text not null default '',
  status text not null default '未完成',
  completion text not null default '-',
  photo text not null default '-',
  operator text not null default ''
);

create table if not exists ot_aquaculturestaffperformancems.t_work (
  wid integer generated by default as identity primary key,
  uid integer not null references ot_aquaculturestaffperformancems.t_user(uid) on delete cascade,
  data text not null default '',
  remarks text not null default '',
  worklist text not null default '',
  time text not null default '',
  photo text not null default '-'
);

create table if not exists ot_aquaculturestaffperformancems.t_performance (
  pfmcid integer generated by default as identity primary key,
  uid integer not null references ot_aquaculturestaffperformancems.t_user(uid) on delete cascade,
  period text not null,
  result text not null default '-',
  status text not null default '考核中',
  appeal text not null default '-',
  utime text not null default ''
);

create table if not exists ot_aquaculturestaffperformancems.t_reward (
  rid integer generated by default as identity primary key,
  uid integer not null references ot_aquaculturestaffperformancems.t_user(uid) on delete cascade,
  reason text not null,
  type text not null,
  time text not null default ''
);

insert into ot_aquaculturestaffperformancems.t_department (did, dname, description, ctime, operator) values
  (1, '行政人资部门', '负责人员档案、制度公告、培训与绩效流程维护。', '2026-07-10 09:00:00', 'system'),
  (2, '水产养殖一部', '负责鱼塘巡检、饲喂记录、水质观察和日常任务执行。', '2026-07-10 09:05:00', 'admin1'),
  (3, '水产养殖二部', '负责虾蟹养殖区的生长指标记录、异常上报与绩效配合。', '2026-07-10 09:10:00', 'admin1'),
  (4, '设备与安全部', '负责增氧机、水泵、投喂设备和生产安全检查。', '2026-07-10 09:15:00', 'admin1')
on conflict (did) do update set
  dname = excluded.dname,
  description = excluded.description,
  ctime = excluded.ctime,
  operator = excluded.operator;

insert into ot_aquaculturestaffperformancems.t_position (pid, did, pname, description, requirements) values
  (1, 1, '系统管理员', '维护基础资料、公告、绩效考核与奖惩信息。', '熟悉人员管理、绩效流程和数据维护。'),
  (2, 2, '鱼塘养殖员', '执行鱼塘巡检、投喂、增重记录和任务反馈。', '能够按周期提交工作记录和现场照片。'),
  (3, 3, '虾蟹养殖员', '执行虾蟹养殖区巡检、饲喂和异常记录。', '熟悉虾蟹养殖指标和常见风险。'),
  (4, 4, '设备安全员', '负责设备巡检、安全检查和维护闭环。', '能够记录设备状态并配合绩效复核。')
on conflict (pid) do update set
  did = excluded.did,
  pname = excluded.pname,
  description = excluded.description,
  requirements = excluded.requirements;

insert into ot_aquaculturestaffperformancems.t_user
  (uid, did, pid, username, password, identify, name, sex, age, birthdate, idcard, phone, avatar) values
  (1, 1, 1, 'admin1', 'admin123', '管理员', '王主管', '女', '29', '1997-02-03', 'DEMO-ID-0001', '13800000001', 'user.jpg'),
  (2, 2, 2, 'admin', 'admin', '普通员工', '李四', '男', '24', '2002-01-12', 'DEMO-ID-0002', '13800000002', 'farm-1.jpg'),
  (3, 2, 2, 'lisi', 'lisi123', '普通员工', '李思', '女', '23', '2003-05-06', 'DEMO-ID-0003', '13800000003', 'farm-2.jpg'),
  (4, 3, 3, 'liwu', 'liwu123', '普通员工', '刘五', '男', '31', '1995-08-19', 'DEMO-ID-0004', '13800000004', 'user.jpg')
on conflict (uid) do update set
  did = excluded.did,
  pid = excluded.pid,
  username = excluded.username,
  password = excluded.password,
  identify = excluded.identify,
  name = excluded.name,
  sex = excluded.sex,
  age = excluded.age,
  birthdate = excluded.birthdate,
  idcard = excluded.idcard,
  phone = excluded.phone,
  avatar = excluded.avatar;

insert into ot_aquaculturestaffperformancems.t_notice (nid, title, notice, ctime, operator) values
  (1, '夏季水质巡检安排', '各养殖区每日 8:30 前完成水温、溶氧、饲喂状态记录，异常情况及时提交。', '2026-07-10 10:00:00', 'admin1'),
  (2, '绩效考核提交提醒', '本周绩效考核周期为 2026-07-06 至 2026-07-12，请员工在周日前补齐工作记录。', '2026-07-10 10:15:00', 'admin1'),
  (3, '设备安全检查通知', '设备与安全部本周重点检查增氧机、水泵与投喂设备，相关人员配合留存照片。', '2026-07-10 10:30:00', 'admin1')
on conflict (nid) do update set
  title = excluded.title,
  notice = excluded.notice,
  ctime = excluded.ctime,
  operator = excluded.operator;

insert into ot_aquaculturestaffperformancems.t_live (lid, data, remarks, operator, time) values
  (1, '0.05 - 0.12', '草鱼', 'admin1', '2026-07-10'),
  (2, '0.03 - 0.08', '鲫鱼', 'admin1', '2026-07-10'),
  (3, '0.02 - 0.06', '南美白对虾', 'admin1', '2026-07-10'),
  (4, '0.01 - 0.04', '螃蟹', 'admin1', '2026-07-10')
on conflict (lid) do update set
  data = excluded.data,
  remarks = excluded.remarks,
  operator = excluded.operator,
  time = excluded.time;

insert into ot_aquaculturestaffperformancems.t_task
  (tid, uid, description, stime, etime, status, completion, photo, operator) values
  (1, 2, '完成一号鱼塘上午巡检，记录水温、溶氧与投喂量。', '2026-07-10', '2026-07-10', '已完成', '已完成水质记录，鱼群状态正常。', 'farm-1.jpg', 'admin1'),
  (2, 3, '补充二号鱼塘饲料并观察增重状态。', '2026-07-10', '2026-07-12', '未完成', '-', '-', 'admin1'),
  (3, 4, '检查虾蟹区增氧设备和水泵运行情况。', '2026-07-10', '2026-07-11', '进行中', '已完成设备初检，待复核。', 'farm-2.jpg', 'admin1')
on conflict (tid) do update set
  uid = excluded.uid,
  description = excluded.description,
  stime = excluded.stime,
  etime = excluded.etime,
  status = excluded.status,
  completion = excluded.completion,
  photo = excluded.photo,
  operator = excluded.operator;

insert into ot_aquaculturestaffperformancems.t_work
  (wid, uid, data, remarks, worklist, time, photo) values
  (1, 2, '0.08', '草鱼', '上午投喂 2 次，水面活跃，溶氧指标正常。', '2026-07-10', 'farm-1.jpg'),
  (2, 3, '0.06', '鲫鱼', '完成饲喂记录，发现局部水草偏密，已上报清理。', '2026-07-10', 'farm-2.jpg'),
  (3, 4, '0.03', '南美白对虾', '完成虾蟹区巡检，增氧设备运行正常。', '2026-07-10', 'user.jpg')
on conflict (wid) do update set
  uid = excluded.uid,
  data = excluded.data,
  remarks = excluded.remarks,
  worklist = excluded.worklist,
  time = excluded.time,
  photo = excluded.photo;

insert into ot_aquaculturestaffperformancems.t_performance
  (pfmcid, uid, period, result, status, appeal, utime) values
  (1, 2, '2026-07-06至2026-07-12', '工作记录完整，指标在目标区间内。', '考核通过', '-', '2026-07-10 11:00:00'),
  (2, 3, '2026-07-06至2026-07-12', '-', '考核中', '-', '2026-07-10 11:05:00'),
  (3, 4, '2026-07-06至2026-07-12', '设备记录完整，待补充照片。', '待复核', '-', '2026-07-10 11:10:00')
on conflict (pfmcid) do update set
  uid = excluded.uid,
  period = excluded.period,
  result = excluded.result,
  status = excluded.status,
  appeal = excluded.appeal,
  utime = excluded.utime;

insert into ot_aquaculturestaffperformancems.t_reward (rid, uid, reason, type, time) values
  (1, 2, '巡检记录完整，异常处理及时。', '奖励', '2026-07-10'),
  (2, 3, '饲喂记录缺少一次复核照片。', '提醒', '2026-07-10'),
  (3, 4, '设备巡检提前完成并提交维护建议。', '奖励', '2026-07-10')
on conflict (rid) do update set
  uid = excluded.uid,
  reason = excluded.reason,
  type = excluded.type,
  time = excluded.time;

select setval(pg_get_serial_sequence('ot_aquaculturestaffperformancems.t_department', 'did'), coalesce((select max(did) from ot_aquaculturestaffperformancems.t_department), 1), true);
select setval(pg_get_serial_sequence('ot_aquaculturestaffperformancems.t_position', 'pid'), coalesce((select max(pid) from ot_aquaculturestaffperformancems.t_position), 1), true);
select setval(pg_get_serial_sequence('ot_aquaculturestaffperformancems.t_user', 'uid'), coalesce((select max(uid) from ot_aquaculturestaffperformancems.t_user), 1), true);
select setval(pg_get_serial_sequence('ot_aquaculturestaffperformancems.t_notice', 'nid'), coalesce((select max(nid) from ot_aquaculturestaffperformancems.t_notice), 1), true);
select setval(pg_get_serial_sequence('ot_aquaculturestaffperformancems.t_live', 'lid'), coalesce((select max(lid) from ot_aquaculturestaffperformancems.t_live), 1), true);
select setval(pg_get_serial_sequence('ot_aquaculturestaffperformancems.t_task', 'tid'), coalesce((select max(tid) from ot_aquaculturestaffperformancems.t_task), 1), true);
select setval(pg_get_serial_sequence('ot_aquaculturestaffperformancems.t_work', 'wid'), coalesce((select max(wid) from ot_aquaculturestaffperformancems.t_work), 1), true);
select setval(pg_get_serial_sequence('ot_aquaculturestaffperformancems.t_performance', 'pfmcid'), coalesce((select max(pfmcid) from ot_aquaculturestaffperformancems.t_performance), 1), true);
select setval(pg_get_serial_sequence('ot_aquaculturestaffperformancems.t_reward', 'rid'), coalesce((select max(rid) from ot_aquaculturestaffperformancems.t_reward), 1), true);

grant usage on schema ot_aquaculturestaffperformancems to service_role;
grant select, insert, update, delete on all tables in schema ot_aquaculturestaffperformancems to service_role;
grant usage, select on all sequences in schema ot_aquaculturestaffperformancems to service_role;

create or replace function public.ot_aquaculturestaffperformancems_rest(
  p_table_name text,
  p_method text default 'GET',
  p_query jsonb default '{}'::jsonb,
  p_payload jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  target_schema text := 'ot_aquaculturestaffperformancems';
  allowed_tables text[] := array[
    't_department',
    't_position',
    't_user',
    't_notice',
    't_live',
    't_task',
    't_work',
    't_performance',
    't_reward'
  ];
  where_sql text := '';
  order_sql text := '';
  limit_sql text := '';
  sql_text text;
  result jsonb;
  item_key text;
  item_value text;
  order_value text;
  order_col text;
  order_dir text;
  insert_cols text;
  insert_vals text;
  set_sql text;
begin
  if not p_table_name = any(allowed_tables) then
    raise exception 'table is not allowed: %', p_table_name;
  end if;

  for item_key, item_value in select key, value from jsonb_each_text(coalesce(p_query, '{}'::jsonb)) loop
    if item_key in ('select', 'order', 'limit') then
      continue;
    end if;

    if not exists (
      select 1
      from information_schema.columns c
      where c.table_schema = target_schema
        and c.table_name = p_table_name
        and c.column_name = item_key
    ) then
      raise exception 'column is not allowed: %', item_key;
    end if;

    if item_value like 'eq.%' then
      where_sql := where_sql || format(' and %I = %L', item_key, substring(item_value from 4));
    else
      where_sql := where_sql || format(' and %I::text ilike %L', item_key, '%' || item_value || '%');
    end if;
  end loop;

  if where_sql <> '' then
    where_sql := ' where ' || substring(where_sql from 6);
  end if;

  order_value := p_query ->> 'order';
  if order_value is not null and order_value <> '' then
    order_col := split_part(order_value, '.', 1);
    order_dir := lower(nullif(split_part(order_value, '.', 2), ''));
    if order_dir not in ('asc', 'desc') then
      order_dir := 'asc';
    end if;
    if exists (
      select 1
      from information_schema.columns c
      where c.table_schema = target_schema
        and c.table_name = p_table_name
        and c.column_name = order_col
    ) then
      order_sql := format(' order by %I %s', order_col, order_dir);
    end if;
  end if;

  if (p_query ->> 'limit') ~ '^[0-9]+$' then
    limit_sql := format(' limit %s', p_query ->> 'limit');
  end if;

  if upper(p_method) = 'GET' then
    sql_text := format(
      'select coalesce(jsonb_agg(to_jsonb(r)), ''[]''::jsonb) from (select * from %I.%I%s%s%s) r',
      target_schema,
      p_table_name,
      where_sql,
      order_sql,
      limit_sql
    );
    execute sql_text into result;
    return result;
  end if;

  if upper(p_method) = 'POST' then
    select
      string_agg(format('%I', key), ', '),
      string_agg(format('%L', value), ', ')
    into insert_cols, insert_vals
    from jsonb_each_text(coalesce(p_payload, '{}'::jsonb)) p
    where exists (
      select 1
      from information_schema.columns c
      where c.table_schema = target_schema
        and c.table_name = p_table_name
        and c.column_name = p.key
    );

    if insert_cols is null then
      raise exception 'payload has no valid columns';
    end if;

    sql_text := format(
      'with changed as (insert into %I.%I (%s) values (%s) returning *) select coalesce(jsonb_agg(to_jsonb(changed)), ''[]''::jsonb) from changed',
      target_schema,
      p_table_name,
      insert_cols,
      insert_vals
    );
    execute sql_text into result;
    return result;
  end if;

  if upper(p_method) = 'PATCH' then
    select string_agg(format('%I = %L', key, value), ', ')
    into set_sql
    from jsonb_each_text(coalesce(p_payload, '{}'::jsonb)) p
    where exists (
      select 1
      from information_schema.columns c
      where c.table_schema = target_schema
        and c.table_name = p_table_name
        and c.column_name = p.key
    );

    if set_sql is null then
      raise exception 'payload has no valid columns';
    end if;

    sql_text := format(
      'with changed as (update %I.%I set %s%s returning *) select coalesce(jsonb_agg(to_jsonb(changed)), ''[]''::jsonb) from changed',
      target_schema,
      p_table_name,
      set_sql,
      where_sql
    );
    execute sql_text into result;
    return result;
  end if;

  if upper(p_method) = 'DELETE' then
    sql_text := format(
      'with changed as (delete from %I.%I%s returning *) select coalesce(jsonb_agg(to_jsonb(changed)), ''[]''::jsonb) from changed',
      target_schema,
      p_table_name,
      where_sql
    );
    execute sql_text into result;
    return result;
  end if;

  raise exception 'method is not allowed: %', p_method;
end;
$$;

grant execute on function public.ot_aquaculturestaffperformancems_rest(text, text, jsonb, jsonb) to service_role;

notify pgrst, 'reload schema';
